# Generated by Django 4.2.9 on 2025-12-16 13:18

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('contact_preferences', models.JSONField(blank=True, default=dict)),
                ('profile_visibility', models.CharField(choices=[('EVERYONE', 'Everyone'), ('TEAM_MEMBERS', 'Team Members Only'), ('PRIVATE', 'Private')], default='EVERYONE', max_length=20)),
                ('share_analytics', models.BooleanField(default=False, help_text='Whether user shares analytics data')),
                ('pincode', models.CharField(blank=True, help_text='Pincode/ZIP code for location-based services', max_length=10)),
                ('service_type', models.CharField(blank=True, help_text='Service type for agents (e.g., Electronics, Appliances, etc.)', max_length=50)),
                ('service_card_id', models.CharField(blank=True, help_text='Service card/ID for agent verification', max_length=50, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether agent is verified by admin')),
                ('total_assigned_cases', models.IntegerField(default=0, help_text='Total cases assigned to this agent')),
                ('total_resolved_cases', models.IntegerField(default=0, help_text='Total cases resolved by this agent')),
                ('current_active_cases', models.IntegerField(default=0, help_text='Currently active cases assigned to this agent')),
                ('average_resolution_time_hours', models.FloatField(default=0.0, help_text='Average time to resolve cases in hours')),
                ('performance_rating', models.FloatField(default=0.0, help_text='Average performance rating from feedback')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
