# Generated by Django 4.2.9 on 2025-12-19 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_complaint_created', models.BooleanField(default=True)),
                ('email_complaint_assigned', models.BooleanField(default=True)),
                ('email_complaint_status_changed', models.BooleanField(default=True)),
                ('email_complaint_resolved', models.BooleanField(default=True)),
                ('email_comment_added', models.BooleanField(default=True)),
                ('email_feedback_received', models.BooleanField(default=True)),
                ('email_assignment_request', models.BooleanField(default=True)),
                ('email_sla_breach', models.BooleanField(default=True)),
                ('inapp_all_notifications', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('COMPLAINT_CREATED', 'Complaint Created'), ('COMPLAINT_ASSIGNED', 'Complaint Assigned'), ('COMPLAINT_STATUS_CHANGED', 'Status Changed'), ('COMPLAINT_RESOLVED', 'Complaint Resolved'), ('COMPLAINT_REOPENED', 'Complaint Reopened'), ('COMMENT_ADDED', 'Comment Added'), ('FEEDBACK_RECEIVED', 'Feedback Received'), ('ASSIGNMENT_REQUEST', 'Assignment Request'), ('ASSIGNMENT_APPROVED', 'Assignment Approved'), ('ASSIGNMENT_REJECTED', 'Assignment Rejected'), ('SLA_BREACH', 'SLA Breach'), ('ESCALATION', 'Escalation'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional notification data'),
        ),
        migrations.AddField(
            model_name='notification',
            name='module',
            field=models.CharField(choices=[('CUSTOMER', 'Customer Module'), ('AGENT', 'Agent Module'), ('ADMIN', 'Admin Module'), ('SYSTEM', 'System Module')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Push'), ('SMS', 'SMS'), ('IN_APP', 'In-App')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category', 'sent_at'], name='notificatio_categor_b6c285_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['module', 'user'], name='notificatio_module_e60a51_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
