# Generated by Django 4.2.9 on 2026-01-05 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_notificationpreference_notification_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('WEB', 'Web Browser'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='WEB', max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcm_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='fcm_tokens_user_id_356d47_idx'), models.Index(fields=['token'], name='fcm_tokens_token_25aa7b_idx')],
            },
        ),
    ]
