# Generated by Django 4.2.9 on 2026-01-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_agentassignmentrequest'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE complaints_complaint DROP COLUMN IF EXISTS billing_amount;',
            reverse_sql='-- No reverse operation',
        ),
    ]
